# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7445a74da88c78e606680be96ae483858f8a72532e2a6db33dbd88d86e0811feb514cec18eb1c66e64838c0991ec72685ed3ebf1af4832e626f611b632135fcf

test:
  secret_key_base: 8f3c2c5f7af322dbac6c6bc77428a3d163226db55bff77c016806b57daea2dd851cbed6a8fb57c6a6cc98ef5fffd0f0655d2fd6704e84b57c8460946aa44c242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
